### ISSUE TITLE
Unable to draw RGB rectangles on grayscale images

### ISSUE THREAD

**Issue by ghost** [13952522076/hpc_yolo3#2]
### Problem
Discovered that the program was unable to draw its colored rectangles on grayscale images due to lack of color channels. This bug would cause the program to abort execution.

### Solution
By converting the grayscale image to RGB, the program could safely use ImageDraw to create colored rectangles.
I am unable to upload the altered py file here. However, the instructions for applying the fix for the bug are simple. Include this line of code below on line 82 of the yolo.py file in the git:
`image = image.convert('RGB')`

**Comment by ma-xu** [comment]
Thank you for your help. I will add it to the project.
